spring.application.name=ForgeHubs
server.port=8081





# ==========================================
# DATABASE - MYSQL
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/forgehub
spring.datasource.username=root
spring.datasource.password=riddesh123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# THYMELEAF
# ==========================================

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


