spring.application.name=ForgeHubs


# ==========================================
# DATABASE - MYSQL
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/forgehub
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ==========================================
# THYMELEAF
# ==========================================

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# ==========================================
# JWT
# ==========================================

jwt.secret=ForgeHubsSecretKeyForJwtAuthentication2026VeryLongSecretKey
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000


# ==========================================
# EMAIL - GMAIL SMTP
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=admindemo039@gmail.com
spring.mail.password=srpw vudb qtgu kjlz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true